# Generated by Django 4.2.10 on 2025-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
