# Generated by Django 3.2 on 2025-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250408_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='amis',
            field=models.ManyToManyField(related_name='_users_citoyen_amis_+', to='users.Citoyen'),
        ),
    ]
