# Generated by Django 3.2 on 2025-04-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_citoyen_amis'),
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='relation',
        ),
        migrations.AddField(
            model_name='ressource',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to='users.citoyen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ressource',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Si activé, seuls les amis peuvent voir cette ressource'),
        ),
    ]
