# Generated by Django 3.2 on 2025-04-09 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ressource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.type'),
        ),
    ]
