# Generated by Django 3.2 on 2025-04-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_add_ressources_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
