# Generated by Django 4.2.10 on 2025-05-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0005_connectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
