version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - livekit
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devsecret

  redis:
    image: redis:alpine

  livekit:
    image: livekit/livekit-server
    restart: always
    ports:
      - "7880:7880"
      - "7881:7881"

    environment:
      LIVEKIT_KEYS: "devkey: devsecret"


volumes:
  postgres_data: