# Generated by Django 3.2 on 2025-04-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('score', models.FloatField(null=True)),
                ('id_address', models.CharField(blank=True, max_length=50, null=True)),
                ('citycode', models.CharField(blank=True, max_length=10, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('housenumber', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('importance', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Recherche d'adresse",
                'verbose_name_plural': "Recherches d'adresses",
            },
        ),
        migrations.CreateModel(
            name='HealthFacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('wheelchair', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('external_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='cartography.healthfacilitytype')),
            ],
        ),
        migrations.AddIndex(
            model_name='addresssearch',
            index=models.Index(fields=['query'], name='cartography_query_e319fe_idx'),
        ),
        migrations.AddIndex(
            model_name='addresssearch',
            index=models.Index(fields=['city'], name='cartography_city_ce32c9_idx'),
        ),
        migrations.AddIndex(
            model_name='addresssearch',
            index=models.Index(fields=['postcode'], name='cartography_postcod_af275e_idx'),
        ),
        migrations.AddIndex(
            model_name='addresssearch',
            index=models.Index(fields=['created_at'], name='cartography_created_0f2e87_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['facility_type'], name='cartography_facilit_8de1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['city'], name='cartography_city_ab2225_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['department'], name='cartography_departm_0fb695_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['is_active'], name='cartography_is_acti_cc01f8_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['wheelchair'], name='cartography_wheelch_0574dd_idx'),
        ),
    ]
